"""CLI entrypoint for git-workflow-automator."""

import argparse
import sys
from pathlib import Path


def cmd_start(args):
    """Start a new branch workflow."""
    print(f"[{'DRY RUN' if args.dry_run else 'EXECUTING'}] start: Creating new branch")
    if args.verbose:
        print(f"  Branch name: {args.branch if hasattr(args, 'branch') and args.branch else '<auto-generated>'}")
    return 0


def cmd_commit(args):
    """Commit changes with automated message generation."""
    print(f"[{'DRY RUN' if args.dry_run else 'EXECUTING'}] commit: Committing changes")
    if args.verbose:
        print(f"  Message: {args.message if hasattr(args, 'message') and args.message else '<auto-generated>'}")
    return 0


def cmd_sync(args):
    """Sync branch with remote and resolve conflicts."""
    print(f"[{'DRY RUN' if args.dry_run else 'EXECUTING'}] sync: Syncing with remote")
    if args.verbose:
        print(f"  Remote: {args.remote if hasattr(args, 'remote') and args.remote else 'origin'}")
    return 0


def cmd_pr(args):
    """Create or update pull request."""
    print(f"[{'DRY RUN' if args.dry_run else 'EXECUTING'}] pr: Managing pull request")
    if args.verbose:
        print(f"  Action: {args.action if hasattr(args, 'action') and args.action else 'create'}")
    return 0


def cmd_doctor(args):
    """Check repository and tool health."""
    print(f"[{'DRY RUN' if args.dry_run else 'EXECUTING'}] doctor: Running diagnostics")
    print("✓ Git repository detected")
    print("✓ Git configured")
    print("✓ Remote configured")
    return 0


def _copilot_log_template(project_name: str, prompts: int) -> str:
    sections = []
    for idx in range(1, prompts + 1):
        sections.append(
            f"## Prompt {idx}\n"
            "- Prompt:\n"
            "- Copilot output summary:\n"
            "- What I kept:\n"
            "- What I changed manually:\n"
            "- Files touched:\n"
        )
    body = "\n".join(sections)
    return (
        f"# Copilot CLI Usage Log for {project_name}\n\n"
        "Use this file as challenge evidence for Copilot-assisted development.\n\n"
        f"{body}\n"
    )


def _dev_submission_template(project_name: str) -> str:
    return f"""# DEV Submission Draft: {project_name}

## What I Built
- Git Workflow Automator (`gwa`) to streamline Git actions from the terminal.

## Challenge Prompt
Built using GitHub Copilot CLI, with iterative prompting for scaffolding, policy rules, audit logging, and tests.

## Demo
- Repo:
- Video:
- Screenshots:

## How to Run
```bash
python3 -m venv .venv
source .venv/bin/activate
python -m pip install -U pip setuptools wheel
python -m pip install -e '.[dev]'
pytest -q
gwa --help
```

## Copilot CLI Usage
Reference `COPILOT_LOG.md` for prompt-by-prompt evidence.

## Judging Criteria Mapping
### Use of GitHub Copilot CLI
- Included prompts, outputs, and manual refinements in `COPILOT_LOG.md`.

### Usability and User Experience
- Simple commands with dry-run support and diagnostics.

### Originality and Creativity
- Git workflow pain-point focused automation with policy + audit readiness.

## What I Learned
- Copilot CLI accelerates iteration when paired with strict validation/tests.
"""


def _write_if_needed(path: Path, content: str, force: bool) -> str:
    if path.exists() and not force:
        return f"SKIP {path} (already exists; use --force to overwrite)"
    path.write_text(content, encoding="utf-8")
    return f"WRITE {path}"


def cmd_init(args):
    """Generate challenge submission scaffolding automatically."""
    root = Path.cwd()
    project_name = args.project_name or root.name

    copilot_log = root / "COPILOT_LOG.md"
    dev_submission = root / "DEV_SUBMISSION_TEMPLATE.md"

    messages = [
        _write_if_needed(copilot_log, _copilot_log_template(project_name, args.prompts), args.force),
        _write_if_needed(dev_submission, _dev_submission_template(project_name), args.force),
    ]

    for msg in messages:
        print(msg)

    print("Done. Fill in the generated files before submitting.")
    return 0


def main():
    """Main CLI entrypoint."""
    parser = argparse.ArgumentParser(
        prog="gwa",
        description="Git Workflow Automator - Automate your git workflows"
    )
    parser.add_argument(
        "--version",
        action="version",
        version="%(prog)s 0.1.0"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose output"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without executing"
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init command
    parser_init = subparsers.add_parser(
        "init",
        aliases=["/init"],
        help="Generate Copilot challenge scaffolding files"
    )
    parser_init.add_argument("--project-name", help="Project name for templates")
    parser_init.add_argument("--prompts", type=int, default=8, help="Number of prompt sections for COPILOT_LOG.md")
    parser_init.add_argument("--force", action="store_true", help="Overwrite existing template files")
    parser_init.set_defaults(func=cmd_init)

    # start command
    parser_start = subparsers.add_parser("start", help="Start a new branch workflow")
    parser_start.add_argument("branch", nargs="?", help="Branch name (optional)")
    parser_start.set_defaults(func=cmd_start)

    # commit command
    parser_commit = subparsers.add_parser("commit", help="Commit changes with automated messages")
    parser_commit.add_argument("-m", "--message", help="Commit message (optional)")
    parser_commit.set_defaults(func=cmd_commit)

    # sync command
    parser_sync = subparsers.add_parser("sync", help="Sync branch with remote")
    parser_sync.add_argument("--remote", default="origin", help="Remote name (default: origin)")
    parser_sync.set_defaults(func=cmd_sync)

    # pr command
    parser_pr = subparsers.add_parser("pr", help="Create or update pull request")
    parser_pr.add_argument("action", nargs="?", default="create", choices=["create", "update"], help="PR action")
    parser_pr.set_defaults(func=cmd_pr)

    # doctor command
    parser_doctor = subparsers.add_parser("doctor", help="Check repository and tool health")
    parser_doctor.set_defaults(func=cmd_doctor)

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 0

    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
